### PR TITLE
Gyndol, Riffol and Nereond integration doc

### PR DESCRIPTION
**Pull request by drystone**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Very impressive drawing 👍 

Is this done via PlantUML? If so you can directly check in the source, and use a script like the following to `make` the image:

* Local: https://github.com/riboseinc/metanorma-model-m3d/blob/master/Makefile
* Travis: https://github.com/riboseinc/metanorma-model-m3d/blob/master/.travis.yml

**Comment by drystone** [comment]
@ronaldtse thanks! Yes, PlantUML. The source is in the SVG so I thought I'd use that :)

Can you set branch `master` as default for this repo please. It got confused when the first push was to `docs`!

EDIT: Could you also confirm this is roughly the approach you had in mind when we discussed this on RD? If there are any security flaws now would be the time to get them straightened out.

**Comment by ronaldtse** [comment]
Done!

**Comment by ronaldtse** [comment]
Ah, I see the source inside the SVG now. It's just kind of weird to have the source file included inside a generated artifact... Should extract it out one day.

**Comment by ronaldtse** [comment]
Done in #3 😉

**Pull request merged**
